// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJ_sECaD7OWfJ_sgk2MbDsmrhz29FmR8',
    appId: '1:100215563254:android:76ab8f7cd81ae0fcf49dd7',
    messagingSenderId: '100215563254',
    projectId: 'sleepguard-82799',
    databaseURL: 'https://sleepguard-82799-default-rtdb.firebaseio.com',
    storageBucket: 'sleepguard-82799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx-6ZWhlfMZxpE8epGiZE7RKIUB5VToKc',
    appId: '1:100215563254:ios:c1de05fde733205ff49dd7',
    messagingSenderId: '100215563254',
    projectId: 'sleepguard-82799',
    databaseURL: 'https://sleepguard-82799-default-rtdb.firebaseio.com',
    storageBucket: 'sleepguard-82799.firebasestorage.app',
    iosBundleId: 'br.com.sleepguard.sleepguardApp',
  );
}
